config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolio_items, expect: [:show]
    
  
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :blogs do 
    member do
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">

  <div class="inner">

    <p><%= copyright_generator %></p>

      </div>
          <%= set_source_helper("applicaion") %>
</div>
      </div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Tarun Kurudi</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link'%>

    </nav>
  </div>
</div>

app/views/shared/_blog-nav.html.erb
<div class="blog-masthead">
    <div class="container">
        <nav class="nav blog-nav">
            <%= nav_helper 'nav-link', 'span' %>
            <%= login_helper 'nav-link' %>
        </nav>
    </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
    <p>
        <%= copyright_generator %>
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
    <div class="container">
        <h1 class="blog-title">Blogs</h1>
        <p class="lead blog-description">sub</p>
        <%= link_to 'Create a new Blog', new_blog_path if logged_in?(:site_admin) %>
        <%#= link_to "destroy", destroy_listing_path(listing) if logged_in?(:site_admin) %>
    </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<!-- start sidebar -->
<div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <h4>About</h4>
        <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum.
            Aenean lacinia bibendum nulla sed consectetur.</p>
    </div>

    <div class="sidebar-module">
        <h4>Elsewhere</h4>
        <ol class="list-unstyled social-style">
            <li><a href="#">
                    <%=fa_icon "github" %>
                </a></li>
            <li>
            <li><a href="#">
                    <%=fa_icon "facebook-f" %>
                </a></li>
            <li>
            <li><a href="#">
                    <%=fa_icon "twitter" %>
                </a></li>
        </ol>
    </div>
</div><!-- /.blog-sidebar -->
<!-- end sidebar -->

app/views/shared/_nav.html.erb
<div class="<%= location %>">
       <div>
              <%= link_to "Home", root_path%>
       </div>
       <div>
              <%= link_to "About", about_path%>
       </div>
       <div>
              <%= link_to "Contact", contact_path%>
       </div>
       <div>
              <%= link_to "Blog", blogs_path%>
       </div>
       <div>
              <%= link_to "Portfolio", portfolio_items_path%>
       </div>

</div>

app/views/shared/_portfolio_footer.html.erb
      <footer class="text-muted">
        <div class="container">
          <p class="float-right">
            <p><%= copyright_generator %> || <%= link_to 'view all portfoios', portfolio_items_path %></p>
          <%= set_source_helper("applicaion") %>
        </div>
      </footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
    <div class="container">
        <h1 class="jumbotron-heading">Portfolio</h1>
        <p class="lead text-muted"> A look at all of my portfolios. Starting from my first HTML page through to my work at EDA and also the work I've done post school. </p>
        <p>
        <%= link_to "If you're interested in learning more", about_path, class: 'btn btn-primary' %>
        <%= link_to "If you're interested in contacting me", contact_path, class: 'btn btn-secondary' %>
        
        </p>
    </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 py-4">
                <h4 class="text-white">About</h4>
                <p class="text-muted">This is my personal portfolio, where Iw ill add all my projects. I will build
                    this website further as I myself become a stronger developer.
                    I am to learn many languages and play with a lot of technology. Please enjoy and if you have any
                    questions, please email me!</p>
            </div>
            <div class="col-sm-4 py-4">
                <h4 class="text-white">Explore</h4>
                <ul class="list-unstyled">
                    <%= nav_helper 'text-white', 'li' %>

                    <li>
                        <%= login_helper "text-white"%>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-inverse bg-inverse">
    <div class="container d-flex justify-content-between">
        <a href="#" class="navbar-brand">Tarun Kurudi</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>