config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolio_items, expect: [:show]
    
  
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'

  resources :blogs do 
    member do
      get :toggle_status
    end
  end
  
  root to: 'pages#home'
end

app/models/portfolio_item.rb
class PortfolioItem < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                    reject_if: lambda { |attr| attr['name'].blank?}
    include Placeholder
    validates_presence_of :title, :body, :main_image, :thumb_image
def self.JavaScript
    where(subtitle: 'JavaScript')
end

after_initialize :set_defaults

def set_defaults 
self.main_image ||= Placeholder.image_generator(height: '600', width: '400')
self.thumb_image||= Placeholder.image_generator(height: '350', width: '200')
end
    end

app/controllers/portfolio_items_controller.rb
class PortfolioItemsController < ApplicationController
  layout 'portfolioitem'
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :updtate, :edit]}, site_admin: :all

  
    def index 
        @portfolio_items = PortfolioItem.all
    end

    def new
        @portfolio_item = PortfolioItem.new
        3.times { @portfolio_item.technologies.build }
    end
    def create 
      
        @portfolio_item = PortfolioItem.new(portfolioitem_params)
    
        respond_to do |format|
          if @portfolio_item.save
            format.html { redirect_to portfolio_items_path, notice: 'Your portfilio item is now live.' }
            format.json { render :show, status: :created, location: @portfolio_item }
          else
            format.html { render :new }
            format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
          end
        end
      end
      def edit
        @portfolio_item = PortfolioItem.find(params[:id])
     

      end
      def update
        @portfolio_item = PortfolioItem.find(params[:id])
        respond_to do |format|
          if @portfolio_item.update(portfolioitem_params)
            format.html { redirect_to portfolio_items_path, notice: 'Portfolio item successfully edited.' }
            format.json { render :show, status: :ok, location: @portfolio_item }
          else
            format.html { render :edit }
            format.json { render json: @portfolio_item.errors, status: :unprocessable_entity }
          end
        end
      end
      def show
        @portfolio_item = PortfolioItem.find(params[:id])
      end
      def destroy
        
        @portfolio_item = PortfolioItem.find(params[:id])
        # @portfolio_item = PortfolioItem.find(1)
        
        @portfolio_item.destroy
        respond_to do |format|
          format.html { redirect_to portfolio_items_path, notice: 'Portfolio item was successfully destroyed.' }
          format.json { head :no_content }
        end
      end
      private
      def portfolioitem_params
        params.require(:portfolio_item).permit(:title,
                                                 :subtitle,
                                                 :thumb_image,
                                                 :main_image,
                                                 :body,
                                                  technologies_attributes: [:name])
      end
end

app/helpers/portfolio_items_helper.rb
module PortfolioItemsHelper
end

app/views/portfolio_items/_form.html.erb
<%= form_with(model: @portfolio_item, local: true) do |form| %>
  <div class='row'>
    <div class="col-md-6">
      <h1>Create a new Portfolio Item</h1>     
        <div class="form-group">
          <%= form.label :title %>
          <%= form.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :subtitle %>
          <%= form.text_field :subtitle, class: 'form-control'  %>
        </div>
      </div>
    
    <div class="col-md-6">
  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 10  %>
  
      </div>
    </div>
  </div>

  <hr>

  
  <div class="col-md-12">
      <h2> Technologies Used </h2>
        <div>
        <%= form.fields_for :technologies do |technology_form| %>
        <div class="form-group">
            <%= technology_form.label :name%>
            <%= technology_form.text_field :name, class: 'form-control' %>
        </div>
        <% end %>
      </div>

  <div class="form-group">
    <%= form.label :thumb_image %>
    <%= form.text_field :thumb_image, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary'  %>
             </div>
          </div>
    <% end %>
    
    

app/views/portfolio_items/_portfolio_item.html.erb
 <div class="card">
        <%= image_tag portfolio_item.thumb_image  unless portfolio_item.thumb_image.nil?%>
        <p class="card-text"><span><%= link_to portfolio_item.title, portfolio_item_path(portfolio_item)%></span>
        <%= portfolio_item.subtitle%>
        </p>
         </div> 
       

app/views/portfolio_items/edit.html.erb
<div class="container portfolio-form"> 
    <%= render 'form', portfolio_item: @portfolio_item%>
</div>

app/views/portfolio_items/index.html.erb
 <div class="album text-muted">
      <div class="container">

        <div class="row">

        <h1>Portfolio Items</h1>

              <%= render @portfolio_items%>
            </div>
        </div>
   </div>

app/views/portfolio_items/new.html.erb
<div class="container portfolio-form"> 

    <%= render 'form', portfolio_item: @portfolio_item%>

</div>

app/views/portfolio_items/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-7">
             <%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>

        </div>    
            <div class="col-md-5">
            <h1><%= @portfolio_item.title%></h1>
                <em><%= @portfolio_item.subtitle%></em>
                <p><%= @portfolio_item.body%></p>

                <h3>Technologies Used:</h3>

                <% @portfolio_item.technologies.each do |t|%>
                <p><%= t.name %></p>
                <% end %>
        </div>

    </div>


</div>


   
    